# Generated by Django 5.1.7 on 2025-04-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_confirmemail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuser",
            name="country",
        ),
    ]
