# Generated by Django 5.1.7 on 2025-06-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="order",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="product",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="updated_at",
        ),
    ]
