# Generated by Django 5.1.7 on 2025-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_dealoftheday"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
