# Generated by Django 5.1.7 on 2025-06-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_brand_category_is_active_product_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
