# Generated by Django 5.1.7 on 2025-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pincode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pincode", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "Pincode",
                "verbose_name_plural": "Pincodes",
            },
        ),
    ]
